# to have the hostname in /actuator/info
info:
  hostname: ${HOSTNAME}

server:
  # for springdoc swagger-ui behind a reverse proxy (X-FORWARDED-*)
  forward-headers-strategy: framework
  # for exception messages in the returned json for errors
  error:
    include-message: always

logging:
  level:
    # To print db information at startup for postgres
    com.zaxxer.hikari.HikariConfig: DEBUG

spring:
  # to have webservices connect to localhost in IDEs
  profiles:
    active: default,local

  # to allow to upload big networks
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 103MB
  codec:
    max-in-memory-size: 100MB

  # rabbitmq default host/port
  rabbitmq:
    addresses: rabbitmq
    port: 5672

  # for now, for both r2dbc and jdbc. Also for now with the same user
  # as the app, but this should be changed
  liquibase:
    url: jdbc:${dbUrl}
    user: ${login}
    password: ${password}


  # for microservices with r2dbc
  r2dbc:
    url: r2dbc:${dbUrl}
    username: ${login}
    password: ${password}
    pool:
      # note: r2dbc pool 0.8.x (and probably 0.9.x) doesn't have a minimumIdle, so it will close all connections if idle.
      # This is still better than having many connections open and idle. Someday if they add support we can configure minimumIdle here
      # 1 connection instead of 10 at startup
      initial-size: 1

  # for microservices with jpa/hibernate
  datasource:
    url: jdbc:${dbUrl}
    username: ${login}
    password: ${password}

    # we have many microservices connecting to the same db,
    # change the minimum idle from 10 to 1 by default
    hikari:
      minimum-idle: 1

  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: validate
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        format_sql: true
        # Used when action: create is uncommented
        hbm2ddl:
          delimiter: ;
      # Uncomment action to automatically generate the database sql schema file
      javax:
        persistence:
          schema-generation:
            scripts:
              #action: create
              create-target: src/main/resources/${dbname}.sql
              create-source: metadata

  # for microservices with elasticsearch
  data:
    elasticsearch:
      enabled: false
      host: elasticsearch
      port: 9200
      client:
        timeout: 60  # Seconds
  # disable reactive client autoconfiguration because we don't use it and it is
  # not configured so it tries to connect to localhost which fails. This means
  # we get an ugly error message at startup, and more importantly that the
  # health probes fail, so things like k8s think the server is not working and
  # don't route traffic to it and keep the previous deployment. We have to do
  # this because the reactiveclient is automatically used by springboot when
  # starter-webflux is used.
  autoconfigure:
    exclude:
      - org.springframework.boot.actuate.autoconfigure.elasticsearch.ElasticSearchReactiveHealthContributorAutoConfiguration
      - org.springframework.boot.autoconfigure.data.elasticsearch.ReactiveElasticsearchRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.data.elasticsearch.ReactiveElasticsearchRestClientAutoConfiguration

# customQuery allows a microservice to set query parameters specific to itself.
# if customQuery is empty, set queryBegin to "?", otherwise set it to "&".
# this allow the user to add additional query elements common to all microservices
# and to use the appropriate leading character depending on whether the microsevice
# uses custom query parameters or not. customQueryBegin in this file must always be '?',
# it is present only to be able to be overriden by deployments in the
# manyschemas mode. It is used only for microservices that have predefined
# query parameters, and it must be used if customQuery is not empty, otherwise
# the manyschema mode doesn't work, so define it everywhere because it doesn't
# hurt.
queryBegin: '?'
customQueryBegin: '?'
customQuery:
#dbName:

powsybl-ws:
  # To set elasticsearch index names prefixes (default empty)
  # please use a separator '_' at prefix end for readiness
  elasticsearch:
    index:
      prefix: 